# Use with: docker compose -f docker-compose.yml -f docker-compose.watch.yml up --watch
services:
  api:
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app/backend
  ui:
    develop:
      watch:
        - action: rebuild
          path: ./frontend/react
          ignore:
            - node_modules/
            - dist/
