[project]
name = "learning-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "bcrypt>=4.1.2",
    "pandas>=1.4.0,<3",
    "streamlit>=1.41.0",
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.27.0",
    "requests>=2.31.0",
    "ruff>=0.14.14",
    "pytest>=8.0.0",
    "httpx>=0.28.1",
]

[tool.ruff]
line-length = 128

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["backend", "frontend"]
combine-as-imports = true
force-sort-within-sections = true
lines-after-imports = 2
order-by-type = false
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
