[[pages]]
path = "frontend/Home.py"
name = "Home"

[[pages]]
path = "frontend/pages/Paths.py"
name = "Paths"

[[pages]]
path = "frontend/pages/MyPaths.py"
name = "My Paths"

[[pages]]
path = "frontend/pages/Courses.py"
name = "Courses"

[[pages]]
path = "frontend/pages/MyCourses.py"
name = "My Courses"
