import pytest


pytestmark = pytest.mark.anyio


async def _login(app_client, username: str, password: str) -> str:
    response = await app_client.post("/auth/login", json={"username": username, "password": password})
    assert response.status_code == 200
    return str(response.json()["token"])


async def _login_admin(app_client) -> str:
    return await _login(app_client, "admin", "admin")


async def _create_user(app_client, token: str, username: str, role: str = "user") -> None:
    response = await app_client.post(
        "/auth/users",
        json={"username": username, "password": "pass123", "role": role},
        headers={"X-Session-Token": token},
    )
    assert response.status_code in (200, 409)


@pytest.mark.integration
async def test_teams_list_requires_auth(app_client):
    """Listing /teams/mine requires authentication."""
    response = await app_client.get("/teams/mine")
    assert response.status_code == 401


@pytest.mark.integration
async def test_team_create_list_and_get_detail(app_client):
    """Users can create teams and see them in /teams/mine."""
    token = await _login_admin(app_client)

    created = await app_client.post(
        "/teams",
        json={"name": "Backend Guild", "description": "API reviews"},
        headers={"X-Session-Token": token},
    )
    assert created.status_code == 200
    team = created.json()
    team_id = int(team["id"])
    assert team["name"] == "Backend Guild"
    assert team["owner_user_id"] == "admin"
    assert team["member_count"] == 1
    assert team["my_role"] == "owner"
    assert len(team["members"]) == 1

    mine = await app_client.get("/teams/mine", headers={"X-Session-Token": token})
    assert mine.status_code == 200
    mine_rows = mine.json()
    matching = [row for row in mine_rows if int(row.get("id") or 0) == team_id]
    assert len(matching) == 1

    detail = await app_client.get(f"/teams/{team_id}", headers={"X-Session-Token": token})
    assert detail.status_code == 200
    assert int(detail.json()["id"]) == team_id


@pytest.mark.integration
async def test_team_member_management_permissions(app_client):
    """Only owner/admin can manage team members."""
    admin_token = await _login_admin(app_client)
    await _create_user(app_client, admin_token, "alice")
    await _create_user(app_client, admin_token, "bob")
    await _create_user(app_client, admin_token, "charlie")

    alice_token = await _login(app_client, "alice", "pass123")
    bob_token = await _login(app_client, "bob", "pass123")

    create_team = await app_client.post(
        "/teams",
        json={"name": "Data Team", "description": ""},
        headers={"X-Session-Token": alice_token},
    )
    assert create_team.status_code == 200
    team_id = int(create_team.json()["id"])

    add_bob = await app_client.post(
        f"/teams/{team_id}/members",
        json={"user_id": "bob", "role": "member"},
        headers={"X-Session-Token": alice_token},
    )
    assert add_bob.status_code == 200
    assert add_bob.json()["user_id"] == "bob"

    bob_forbidden = await app_client.post(
        f"/teams/{team_id}/members",
        json={"user_id": "charlie", "role": "member"},
        headers={"X-Session-Token": bob_token},
    )
    assert bob_forbidden.status_code == 403

    remove_owner_forbidden = await app_client.delete(
        f"/teams/{team_id}/members/alice",
        headers={"X-Session-Token": alice_token},
    )
    assert remove_owner_forbidden.status_code == 400


@pytest.mark.integration
async def test_non_member_cannot_access_team_detail(app_client):
    """Non-members cannot view other teams."""
    admin_token = await _login_admin(app_client)
    await _create_user(app_client, admin_token, "alice")
    await _create_user(app_client, admin_token, "bob")

    alice_token = await _login(app_client, "alice", "pass123")
    bob_token = await _login(app_client, "bob", "pass123")

    create_team = await app_client.post(
        "/teams",
        json={"name": "Private Team", "description": ""},
        headers={"X-Session-Token": alice_token},
    )
    assert create_team.status_code == 200
    team_id = int(create_team.json()["id"])

    detail = await app_client.get(f"/teams/{team_id}", headers={"X-Session-Token": bob_token})
    assert detail.status_code == 403


@pytest.mark.integration
async def test_team_activity_lists_member_events(app_client):
    """Team activity returns share and review events generated by team members."""
    admin_token = await _login_admin(app_client)
    await _create_user(app_client, admin_token, "alice")
    await _create_user(app_client, admin_token, "bob")

    alice_token = await _login(app_client, "alice", "pass123")
    bob_token = await _login(app_client, "bob", "pass123")

    create_team = await app_client.post(
        "/teams",
        json={"name": "Review Team", "description": ""},
        headers={"X-Session-Token": alice_token},
    )
    assert create_team.status_code == 200
    team_id = int(create_team.json()["id"])

    add_bob = await app_client.post(
        f"/teams/{team_id}/members",
        json={"user_id": "bob", "role": "member"},
        headers={"X-Session-Token": alice_token},
    )
    assert add_bob.status_code == 200

    created_course = await app_client.post(
        "/courses",
        json={"title": "Team Activity Course", "description": "desc"},
        headers={"X-Session-Token": bob_token},
    )
    assert created_course.status_code == 200
    course_id = int(created_course.json()["id"])

    created_review = await app_client.post(
        f"/courses/{course_id}/reviews",
        json={"rating": 4, "text": "Solid"},
        headers={"X-Session-Token": bob_token},
    )
    assert created_review.status_code == 200

    activity = await app_client.get(f"/teams/{team_id}/activity", headers={"X-Session-Token": alice_token})
    assert activity.status_code == 200
    rows = activity.json()
    assert rows
    assert any(str(row.get("actor") or "") == "bob" for row in rows)
    assert any(str(row.get("event_type") or "") == "course_shared" for row in rows)
    assert any(str(row.get("event_type") or "") == "course_review" for row in rows)


@pytest.mark.integration
async def test_team_activity_includes_video_review_events(app_client):
    """Team activity includes video reviews from team members."""
    admin_token = await _login_admin(app_client)
    await _create_user(app_client, admin_token, "alice")
    await _create_user(app_client, admin_token, "bob")

    alice_token = await _login(app_client, "alice", "pass123")
    bob_token = await _login(app_client, "bob", "pass123")

    create_team = await app_client.post(
        "/teams",
        json={"name": "Video Review Team", "description": ""},
        headers={"X-Session-Token": alice_token},
    )
    assert create_team.status_code == 200
    team_id = int(create_team.json()["id"])

    add_bob = await app_client.post(
        f"/teams/{team_id}/members",
        json={"user_id": "bob", "role": "member"},
        headers={"X-Session-Token": alice_token},
    )
    assert add_bob.status_code == 200

    create_video = await app_client.post(
        "/videos",
        json={
            "title": "Team Activity Video",
            "description": "desc",
            "provider": "YouTube",
            "category": "Programming",
            "url": "https://www.youtube.com/watch?v=team-activity-video",
        },
        headers={"X-Session-Token": bob_token},
    )
    assert create_video.status_code == 200
    video_id = int(create_video.json()["id"])

    created_review = await app_client.post(
        f"/videos/{video_id}/reviews",
        json={"rating": 4, "text": "Solid"},
        headers={"X-Session-Token": bob_token},
    )
    assert created_review.status_code == 200

    activity = await app_client.get(f"/teams/{team_id}/activity", headers={"X-Session-Token": alice_token})
    assert activity.status_code == 200
    rows = activity.json()
    assert rows
    assert any(str(row.get("event_type") or "") == "video_review" for row in rows)
    assert any(str(row.get("target_type") or "") == "video" for row in rows)
