from backend.api.schemas.ai import AiDraftCourse, AiDraftPath, AiPlanRequest, AiPlanResponse
from backend.api.schemas.article_reviews import (
    ArticleReviewCreateRequest,
    ArticleReviewPayload,
    ArticleReviewSummaryItem,
    DeleteArticleReviewResponse,
)
from backend.api.schemas.articles import ArticleCreateRequest, ArticlePayload
from backend.api.schemas.auth import (
    CreateUserRequest,
    CreateUserResponse,
    DeleteUserResponse,
    DisableUserRequest,
    DisableUserResponse,
    LoginRequest,
    LoginResponse,
    LogoutResponse,
    MeResponse,
    ResetPasswordRequest,
    ResetPasswordResponse,
    RoleResponse,
    UserListItem,
)
from backend.api.schemas.common import APIModel, ErrorResponse, HealthResponse
from backend.api.schemas.course_recommendations import (
    CourseRecommendationCreateRequest,
    CourseRecommendationPayload,
    CourseRecommendationSummaryItem,
    DeleteCourseRecommendationResponse,
)
from backend.api.schemas.course_reviews import (
    CourseReviewCreateRequest,
    CourseReviewPayload,
    CourseReviewSummaryItem,
    DeleteCourseReviewResponse,
)
from backend.api.schemas.courses import CourseCreateRequest, CoursePayload, CourseUpdateRequest, DeleteCourseResponse
from backend.api.schemas.notifications import NotificationActivityItem
from backend.api.schemas.path_recommendations import (
    DeletePathRecommendationResponse,
    PathRecommendationCreateRequest,
    PathRecommendationPayload,
    PathRecommendationSummaryItem,
)
from backend.api.schemas.path_reviews import (
    DeletePathReviewResponse,
    PathReviewCreateRequest,
    PathReviewPayload,
    PathReviewSummaryItem,
)
from backend.api.schemas.paths import (
    DeletePathResponse,
    PathCourseItem,
    PathCreateRequest,
    PathDetailResponse,
    PathListItem,
    PathStatusRequest,
    PathStatusResponse,
    PathUpdateRequest,
    SelectedPathItem,
    SelectPathResponse,
    UnselectPathResponse,
)
from backend.api.schemas.tracking import (
    TrackingDeleteRequest,
    TrackingDeleteResponse,
    TrackingRecordPayload,
    TrackingStatsByUserItem,
    TrackingUpsertRequest,
)
from backend.api.schemas.url_preview import UrlPreviewMetadataRequest, UrlPreviewMetadataResponse


__all__ = [
    "APIModel",
    "ErrorResponse",
    "HealthResponse",
    "AiPlanRequest",
    "AiPlanResponse",
    "AiDraftPath",
    "AiDraftCourse",
    "LoginRequest",
    "LoginResponse",
    "MeResponse",
    "LogoutResponse",
    "RoleResponse",
    "CreateUserRequest",
    "CreateUserResponse",
    "UserListItem",
    "ResetPasswordRequest",
    "ResetPasswordResponse",
    "DeleteUserResponse",
    "DisableUserRequest",
    "DisableUserResponse",
    "ArticlePayload",
    "ArticleCreateRequest",
    "ArticleReviewPayload",
    "ArticleReviewCreateRequest",
    "ArticleReviewSummaryItem",
    "DeleteArticleReviewResponse",
    "CoursePayload",
    "CourseCreateRequest",
    "CourseUpdateRequest",
    "DeleteCourseResponse",
    "CourseReviewPayload",
    "CourseReviewCreateRequest",
    "CourseReviewSummaryItem",
    "DeleteCourseReviewResponse",
    "CourseRecommendationPayload",
    "CourseRecommendationCreateRequest",
    "CourseRecommendationSummaryItem",
    "DeleteCourseRecommendationResponse",
    "PathListItem",
    "PathCourseItem",
    "PathDetailResponse",
    "PathCreateRequest",
    "PathUpdateRequest",
    "DeletePathResponse",
    "SelectPathResponse",
    "UnselectPathResponse",
    "PathReviewPayload",
    "PathReviewCreateRequest",
    "PathReviewSummaryItem",
    "DeletePathReviewResponse",
    "PathRecommendationPayload",
    "PathRecommendationCreateRequest",
    "PathRecommendationSummaryItem",
    "DeletePathRecommendationResponse",
    "PathStatusRequest",
    "PathStatusResponse",
    "SelectedPathItem",
    "NotificationActivityItem",
    "TrackingUpsertRequest",
    "TrackingDeleteRequest",
    "TrackingRecordPayload",
    "TrackingDeleteResponse",
    "TrackingStatsByUserItem",
    "UrlPreviewMetadataRequest",
    "UrlPreviewMetadataResponse",
]
